#!/bin/bash

DEFAULT_COMMIT_MESSAGE="Aggiornamento sito $(date +'%Y-%m-%d %H:%M:%S')"

if [ $# -eq 0 ]; then
    COMMIT_MESSAGE="$DEFAULT_COMMIT_MESSAGE"
else
    COMMIT_MESSAGE="$1"
fi

# npm run build

git add .
git commit -m "$COMMIT_MESSAGE"
git push
